#!/bin/bash
sleep 2

cd /home/pi/Python
python tdtool-with-sensors.py -d 2367754
python tdtool-with-sensors.py -d 2777935

while true 
do
  python tdtool-with-sensors.py -d 2367754  >> TempLog.dat
  python tdtool-with-sensors.py -d 2777935  >> TempLog.dat
  sleep 600
done

